import { Lead, Activity, VapiCall, AnalyticsOverview, PipelineData, SourceData } from "@/types";

const demoLeads: Lead[] = [
  {
    id: "rec1",
    name: "John Smith",
    email: "john.smith@techcorp.com",
    phone: "+1-555-0101",
    company: "TechCorp Inc",
    title: "VP of Engineering",
    linkedinUrl: "https://linkedin.com/in/johnsmith",
    leadSource: "LinkedIn",
    status: "Qualified",
    aiScore: 87,
    aiScoreLabel: "Hot 🔥",
    aiInsights: "High-value enterprise lead with strong decision-making authority. Company is in growth phase and actively looking for solutions. Recent LinkedIn activity shows engagement with similar products.",
    keyStrengths: ["Decision maker with budget authority", "Enterprise company (500+ employees)", "Active engagement on LinkedIn", "Corporate email domain"],
    concerns: ["Long enterprise sales cycle", "May require multiple stakeholders"],
    suggestedNextStep: "Schedule a discovery call to discuss their engineering workflow challenges",
    lastContacted: new Date(Date.now() - 2 * 86400000).toISOString(),
    nextFollowUp: new Date(Date.now() + 3 * 86400000).toISOString(),
    notes: "Met at TechConf 2024. Very interested in AI automation.",
    vapiCallStatus: "Completed",
    vapiCallSummary: "John expressed strong interest in automating their CI/CD pipeline. Budget approved for Q1. Wants a detailed proposal by next week.",
    createdAt: new Date(Date.now() - 14 * 86400000).toISOString(),
  },
  {
    id: "rec2",
    name: "Sarah Johnson",
    email: "sarah.j@startup.io",
    phone: "+1-555-0102",
    company: "Startup.io",
    title: "Founder & CEO",
    linkedinUrl: "https://linkedin.com/in/sarahjohnson",
    leadSource: "Referral",
    status: "Contacted",
    aiScore: 92,
    aiScoreLabel: "Hot 🔥",
    aiInsights: "Extremely high-value lead. Founder/CEO with direct budget authority. Referred by existing client which indicates strong buying intent. Startup in Series B stage with funding to spend.",
    keyStrengths: ["Direct decision maker (CEO)", "Referred by existing client", "Series B funded startup", "Urgent timeline mentioned"],
    concerns: ["Startup budget may be limited", "Fast-moving - needs quick follow-up"],
    suggestedNextStep: "Send personalized email referencing the referral and schedule a demo this week",
    lastContacted: new Date(Date.now() - 1 * 86400000).toISOString(),
    nextFollowUp: new Date(Date.now() + 1 * 86400000).toISOString(),
    notes: "Referred by Alex Chen (client). Needs solution ASAP.",
    vapiCallStatus: "Scheduled",
    createdAt: new Date(Date.now() - 7 * 86400000).toISOString(),
  },
  {
    id: "rec3",
    name: "Mike Wilson",
    email: "mike.wilson@gmail.com",
    phone: "+1-555-0103",
    company: "Freelance",
    title: "Consultant",
    leadSource: "Website",
    status: "New",
    aiScore: 28,
    aiScoreLabel: "Cold ❄️",
    aiInsights: "Low priority lead. Personal email domain suggests individual rather than business buyer. Consultant role typically means limited budget and no organizational buying power.",
    keyStrengths: ["Showed interest by visiting website"],
    concerns: ["Personal email (not corporate)", "Freelance/individual - limited budget", "No clear company affiliation", "Consultant role - unlikely decision maker"],
    suggestedNextStep: "Add to nurture email sequence with educational content",
    lastContacted: undefined,
    notes: "",
    vapiCallStatus: "Not Called",
    createdAt: new Date(Date.now() - 3 * 86400000).toISOString(),
  },
  {
    id: "rec4",
    name: "Emily Davis",
    email: "emily.davis@enterprise.co",
    phone: "+1-555-0104",
    company: "Enterprise Solutions Co",
    title: "Director of Operations",
    linkedinUrl: "https://linkedin.com/in/emilydavis",
    leadSource: "Event",
    status: "Proposal",
    aiScore: 78,
    aiScoreLabel: "Hot 🔥",
    aiInsights: "Strong enterprise lead from industry event. Director-level with operational budget authority. Company size indicates substantial deal potential. Multiple touchpoints suggest genuine interest.",
    keyStrengths: ["Director level - budget authority", "Large enterprise company", "Met at industry event (high intent)", "Corporate email domain"],
    concerns: ["Procurement process may be lengthy", "Competitive evaluation likely"],
    suggestedNextStep: "Follow up on the proposal sent last week and address any questions",
    lastContacted: new Date(Date.now() - 5 * 86400000).toISOString(),
    nextFollowUp: new Date(Date.now() + 2 * 86400000).toISOString(),
    notes: "Sent proposal on Monday. Following up this week.",
    vapiCallStatus: "Completed",
    vapiCallSummary: "Emily reviewed the proposal with her team. They have a few questions about implementation timeline and support levels. Overall very positive reception.",
    createdAt: new Date(Date.now() - 21 * 86400000).toISOString(),
  },
  {
    id: "rec5",
    name: "David Chen",
    email: "dchen@midmarket.com",
    phone: "+1-555-0105",
    company: "MidMarket Solutions",
    title: "Head of Technology",
    leadSource: "LinkedIn",
    status: "Contacted",
    aiScore: 65,
    aiScoreLabel: "Warm 🌡️",
    aiInsights: "Mid-range lead with potential. Head of Technology has influence but may need C-suite approval. Mid-market company size suggests moderate deal value. LinkedIn outreach shows some engagement.",
    keyStrengths: ["Technology decision influencer", "Mid-market company with budget", "Engaged with LinkedIn content"],
    concerns: ["May need C-suite approval for purchase", "Mid-market budget constraints", "Engagement level is moderate"],
    suggestedNextStep: "Share a relevant case study and request a 15-minute introductory call",
    lastContacted: new Date(Date.now() - 4 * 86400000).toISOString(),
    nextFollowUp: new Date(Date.now() + 5 * 86400000).toISOString(),
    notes: "Liked our LinkedIn post about AI automation.",
    vapiCallStatus: "No Answer",
    createdAt: new Date(Date.now() - 10 * 86400000).toISOString(),
  },
  {
    id: "rec6",
    name: "Lisa Park",
    email: "lisa@innovatetech.com",
    phone: "+1-555-0106",
    company: "InnovateTech",
    title: "CTO",
    linkedinUrl: "https://linkedin.com/in/lisapark",
    leadSource: "Referral",
    status: "Qualified",
    aiScore: 85,
    aiScoreLabel: "Hot 🔥",
    aiInsights: "High-value CTO lead from referral channel. Technical decision maker with strong buying authority. Company is in growth mode. Referral source adds high credibility.",
    keyStrengths: ["CTO - key technical decision maker", "Referral from trusted source", "Growing technology company", "Corporate email domain"],
    concerns: ["Technical evaluation will be thorough", "May compare with open-source alternatives"],
    suggestedNextStep: "Prepare a technical deep-dive demo tailored to their tech stack",
    lastContacted: new Date(Date.now() - 1 * 86400000).toISOString(),
    nextFollowUp: new Date(Date.now() + 2 * 86400000).toISOString(),
    notes: "Referred by Tom at CloudBase. Interested in our API capabilities.",
    vapiCallStatus: "Completed",
    vapiCallSummary: "Lisa is impressed with the technical capabilities. Wants to do a POC with her engineering team. Timeline: 2 weeks for evaluation.",
    createdAt: new Date(Date.now() - 12 * 86400000).toISOString(),
  },
  {
    id: "rec7",
    name: "Robert Taylor",
    email: "rtaylor@bigcorp.net",
    phone: "+1-555-0107",
    company: "BigCorp International",
    title: "Senior Manager, IT",
    leadSource: "Cold Outreach",
    status: "New",
    aiScore: 45,
    aiScoreLabel: "Warm 🌡️",
    aiInsights: "Moderate potential from cold outreach. Senior Manager has some influence but limited direct budget authority. Large corporation presents both opportunity and complexity.",
    keyStrengths: ["Large enterprise company", "IT department contact", "Corporate email domain"],
    concerns: ["Cold outreach - lower intent", "Manager level - limited authority", "Large org - slow decisions"],
    suggestedNextStep: "Send introductory email with industry-specific value proposition",
    lastContacted: undefined,
    notes: "",
    vapiCallStatus: "Not Called",
    createdAt: new Date(Date.now() - 2 * 86400000).toISOString(),
  },
  {
    id: "rec8",
    name: "Amanda Foster",
    email: "amanda.f@scaleup.io",
    phone: "+1-555-0108",
    company: "ScaleUp Inc",
    title: "VP of Sales",
    linkedinUrl: "https://linkedin.com/in/amandafoster",
    leadSource: "Website",
    status: "Won",
    aiScore: 95,
    aiScoreLabel: "Hot 🔥",
    aiInsights: "Converted lead. VP of Sales at a high-growth startup. Quick sales cycle due to urgent need and direct authority. Website visit converted to demo within 24 hours.",
    keyStrengths: ["VP level - direct authority", "High urgency", "Quick decision maker", "Growth-stage company"],
    concerns: [],
    suggestedNextStep: "Onboarding and upsell opportunities in 30 days",
    lastContacted: new Date(Date.now() - 1 * 86400000).toISOString(),
    notes: "Signed contract! ARR: $24,000. Champion for expansion.",
    vapiCallStatus: "Completed",
    vapiCallSummary: "Amanda confirmed the purchase. Very happy with the demo. Plans to expand usage across the sales team in Q2.",
    createdAt: new Date(Date.now() - 30 * 86400000).toISOString(),
  },
  {
    id: "rec9",
    name: "James Wright",
    email: "j.wright@yahoo.com",
    phone: "+1-555-0109",
    company: "",
    title: "Student",
    leadSource: "Website",
    status: "Lost",
    aiScore: 12,
    aiScoreLabel: "Cold ❄️",
    aiInsights: "Very low priority. Personal email, student role, no company affiliation. Likely researching for academic purposes rather than a buying prospect.",
    keyStrengths: ["Website visitor"],
    concerns: ["Personal email domain", "Student - no buying power", "No company affiliation", "No phone provided"],
    suggestedNextStep: "No action needed - add to educational content mailing list",
    lastContacted: new Date(Date.now() - 10 * 86400000).toISOString(),
    notes: "Was looking for pricing info for a school project.",
    vapiCallStatus: "Not Called",
    createdAt: new Date(Date.now() - 15 * 86400000).toISOString(),
  },
  {
    id: "rec10",
    name: "Nicole Martinez",
    email: "nicole@growthagency.com",
    phone: "+1-555-0110",
    company: "Growth Agency",
    title: "Managing Partner",
    linkedinUrl: "https://linkedin.com/in/nicolemartinez",
    leadSource: "Event",
    status: "Contacted",
    aiScore: 55,
    aiScoreLabel: "Warm 🌡️",
    aiInsights: "Moderate lead from event. Managing Partner at an agency - could be a channel partner opportunity. Agency model means potential for multiple client referrals if converted.",
    keyStrengths: ["Managing Partner - decision maker", "Agency - potential for multiple deals", "Met at event (moderate intent)", "Corporate email"],
    concerns: ["Agency may want white-label/reseller pricing", "Different buying motivation than end-user"],
    suggestedNextStep: "Explore partnership opportunity alongside direct sale",
    lastContacted: new Date(Date.now() - 3 * 86400000).toISOString(),
    nextFollowUp: new Date(Date.now() + 4 * 86400000).toISOString(),
    notes: "Interested in partnership model. Discussed at GrowthCon.",
    vapiCallStatus: "Callback Requested",
    createdAt: new Date(Date.now() - 8 * 86400000).toISOString(),
  },
];

const demoActivities: Activity[] = [
  {
    id: "act1",
    activityType: "Call Made",
    leadId: "rec1",
    leadName: "John Smith",
    description: "Discovery call completed. Discussed engineering workflow pain points and AI automation opportunities.",
    outcome: "Positive",
    createdAt: new Date(Date.now() - 2 * 86400000).toISOString(),
  },
  {
    id: "act2",
    activityType: "Email Sent",
    leadId: "rec2",
    leadName: "Sarah Johnson",
    description: "Sent personalized intro email referencing Alex Chen's referral. Included case study link.",
    outcome: "Positive",
    createdAt: new Date(Date.now() - 1 * 86400000).toISOString(),
  },
  {
    id: "act3",
    activityType: "Proposal Sent",
    leadId: "rec4",
    leadName: "Emily Davis",
    description: "Sent detailed proposal with pricing for Enterprise tier. Includes implementation timeline.",
    outcome: "Neutral",
    createdAt: new Date(Date.now() - 5 * 86400000).toISOString(),
  },
  {
    id: "act4",
    activityType: "Meeting Scheduled",
    leadId: "rec6",
    leadName: "Lisa Park",
    description: "Scheduled technical deep-dive demo for next Tuesday at 2pm EST.",
    outcome: "Positive",
    createdAt: new Date(Date.now() - 1 * 86400000).toISOString(),
  },
  {
    id: "act5",
    activityType: "Follow Up",
    leadId: "rec5",
    leadName: "David Chen",
    description: "Sent follow-up LinkedIn message with case study about mid-market automation success.",
    outcome: "No Response",
    createdAt: new Date(Date.now() - 4 * 86400000).toISOString(),
  },
  {
    id: "act6",
    activityType: "Note Added",
    leadId: "rec8",
    leadName: "Amanda Foster",
    description: "Contract signed! $24,000 ARR. Kickoff meeting scheduled for next Monday.",
    outcome: "Positive",
    createdAt: new Date(Date.now() - 1 * 86400000).toISOString(),
  },
  {
    id: "act7",
    activityType: "Call Made",
    leadId: "rec10",
    leadName: "Nicole Martinez",
    description: "Brief call to discuss partnership model. She requested a callback next week with her business partner.",
    outcome: "Neutral",
    createdAt: new Date(Date.now() - 3 * 86400000).toISOString(),
  },
  {
    id: "act8",
    activityType: "Email Sent",
    leadId: "rec7",
    leadName: "Robert Taylor",
    description: "Initial outreach email with enterprise-specific value proposition and ROI calculator link.",
    outcome: "No Response",
    createdAt: new Date(Date.now() - 2 * 86400000).toISOString(),
  },
];

const demoCalls: VapiCall[] = [
  {
    id: "call1",
    leadId: "rec1",
    leadName: "John Smith",
    scheduledAt: new Date(Date.now() - 3 * 86400000).toISOString(),
    completedAt: new Date(Date.now() - 2 * 86400000).toISOString(),
    duration: 847,
    outcome: "Qualified",
    summary: "John expressed strong interest in automating their CI/CD pipeline. Budget approved for Q1. Wants a detailed proposal by next week.",
    status: "Completed",
  },
  {
    id: "call2",
    leadId: "rec2",
    leadName: "Sarah Johnson",
    scheduledAt: new Date(Date.now() + 1 * 86400000).toISOString(),
    status: "Scheduled",
  },
  {
    id: "call3",
    leadId: "rec4",
    leadName: "Emily Davis",
    scheduledAt: new Date(Date.now() - 7 * 86400000).toISOString(),
    completedAt: new Date(Date.now() - 7 * 86400000).toISOString(),
    duration: 623,
    outcome: "Interested",
    summary: "Emily reviewed the proposal with her team. Questions about implementation timeline and support. Overall positive.",
    status: "Completed",
  },
  {
    id: "call4",
    leadId: "rec5",
    leadName: "David Chen",
    scheduledAt: new Date(Date.now() - 5 * 86400000).toISOString(),
    completedAt: new Date(Date.now() - 5 * 86400000).toISOString(),
    duration: 0,
    outcome: "No Answer",
    summary: "Call went to voicemail. Left message about AI automation capabilities.",
    status: "No Answer",
  },
  {
    id: "call5",
    leadId: "rec6",
    leadName: "Lisa Park",
    scheduledAt: new Date(Date.now() - 2 * 86400000).toISOString(),
    completedAt: new Date(Date.now() - 1 * 86400000).toISOString(),
    duration: 1102,
    outcome: "Qualified",
    summary: "Lisa is impressed with technical capabilities. Wants to do a POC with engineering team. Timeline: 2 weeks.",
    status: "Completed",
  },
  {
    id: "call6",
    leadId: "rec8",
    leadName: "Amanda Foster",
    scheduledAt: new Date(Date.now() - 14 * 86400000).toISOString(),
    completedAt: new Date(Date.now() - 14 * 86400000).toISOString(),
    duration: 1456,
    outcome: "Converted",
    summary: "Amanda confirmed purchase. Very happy with demo. Plans to expand across sales team in Q2.",
    status: "Completed",
  },
  {
    id: "call7",
    leadId: "rec10",
    leadName: "Nicole Martinez",
    scheduledAt: new Date(Date.now() + 4 * 86400000).toISOString(),
    status: "Scheduled",
  },
];

export function getDemoLeads(): Lead[] {
  return demoLeads;
}

export function getDemoLead(id: string): Lead | undefined {
  return demoLeads.find((l) => l.id === id);
}

export function getDemoActivities(): Activity[] {
  return demoActivities;
}

export function getDemoActivitiesForLead(leadId: string): Activity[] {
  return demoActivities.filter((a) => a.leadId === leadId);
}

export function getDemoCalls(): VapiCall[] {
  return demoCalls;
}

export function getDemoAnalyticsOverview(): AnalyticsOverview {
  const leads = demoLeads;
  return {
    totalLeads: leads.length,
    hotLeads: leads.filter((l) => (l.aiScore ?? 0) >= 70).length,
    warmLeads: leads.filter((l) => (l.aiScore ?? 0) >= 40 && (l.aiScore ?? 0) < 70).length,
    coldLeads: leads.filter((l) => (l.aiScore ?? 0) < 40).length,
    conversionRate: Math.round((leads.filter((l) => l.status === "Won").length / leads.length) * 100),
    callsScheduledToday: demoCalls.filter((c) => c.status === "Scheduled").length,
  };
}

export function getDemoPipelineData(): PipelineData[] {
  const leads = demoLeads;
  const statuses: Lead["status"][] = ["New", "Contacted", "Qualified", "Proposal", "Won", "Lost"];
  return statuses.map((status) => ({
    status,
    count: leads.filter((l) => l.status === status).length,
  }));
}

export function getDemoSourceData(): SourceData[] {
  const leads = demoLeads;
  const sources: Lead["leadSource"][] = ["Website", "LinkedIn", "Referral", "Cold Outreach", "Event"];
  return sources
    .map((source) => ({
      source: source!,
      count: leads.filter((l) => l.leadSource === source).length,
    }))
    .filter((s) => s.count > 0);
}
